### ISSUE TITLE
OGPのスタイルがテーマに対応していない

### ISSUE THREAD

**Issue by htomine** [increments/mastodon#34]
https://qiitadon.com/@voqn/636

> voqn on qiitadon.com
> @qiita_staff の人に報告するのが正しいのかどうか微妙だけれど、 `status-card__image` とかの OGP リンク展開の方のCSSがデフォルトのCSSのままになってる (CSS上書きするマストドンインスタンスでありがちな見落としパティーン）

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by VoQn** [comment]
@htomine 
PR出せばよかったんだけど、まだインスタンス手元で立ち上げる環境が無いのでテストできないままコミットしちゃうのは気が引けたので取り急ぎ。

こんな感じです。`$ogp-*` なのは説明のための疑似コードぐらいに解釈してください。色変えるだけだったらこれでいいかな

```scss
.status-card {
  background-color: $ogp-background-color;
  color: $ogp-foreground-color;
  border-color: $ogp-frame-border-color;
}
.status-card:hover {
  background-color: $ogp-hover-background-color;
}
.status-card__image {
  background-color: $ogp-frame-color;
}
.status-card__title {
  color: $ogp-title-color;
}
.status-card__description {
  color: $ogp-description-color;
}
```
